spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: discount_watcher_server
    password: secret-password
  rabbitmq:
    host: localhost

application:
  security:
    jwt:
      secret: ldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmada
      expiration-time: 2592000
