spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres
    username: discount_watcher_server
    password: secret-password
  rabbitmq:
    host: ${RABBIT_HOST}

application:
  security:
    jwt:
      secret: ldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmada
      expiration-time: 2592000

logging:
  level:
    root: INFO
