spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres
    username: discount_watcher_server
    password: secret-password
  rabbitmq:
    host: ${RABBIT_HOST}

logging:
  level:
    root: INFO
