server:
  port: 8081
  servlet:
    context-path: /server

spring:
  flyway:
    baseline-on-migrate: true
    default-schema: discount_watcher_schema
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: discount_watcher_schema

application:
  scheduler:
    product:
      update: "0 0 0,12 * * *" # every day at 0:00 and 12:00
  mq:
    input-queue-name: "dw-parser-input"
    output-queue-name: "dw-parser-output"
    output-error-queue-name: "dw-parser-error"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
