spring:
  jpa:
    show-sql=true:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: discount_watcher_schema
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: discount_watcher_server
    password: secret-password
  rabbitmq:
    host: localhost

server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: /dev-certificates/discount-watcher-server.p12
    key-store-password: password
    key-alias: DWS

application:
  security:
    jwt:
      secret: ldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmada
      expiration-time: 2592000
    header:
      authentication: Authorization
  mq:
    input-queue-name: "dw-parser-input"
    output-queue-name: "dw-parser-output"
    output-error-queue-name: "dw-parser-error"

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL:
          DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
