spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres
    username: discount_watcher_server
    password: secret-password
    hikari:
      schema: discount_watcher_schema_test

server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: ${KEY_STORE_PATH}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: DWS

application:
  security:
    jwt:
      secret: ldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmadaldfbjafslnkasfnkasfmada
      expiration-time: 2592000
    header:
      authentication: Authorization
  parser:
    lenta-user-agent-header: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 OPR/89.0.4447.48
    lenta-referer-header: https://lenta.com/
  schedule:
    product-update:
      min-delay: 1000
      max-delay: 3000

logging:
  level:
    root: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
