name: Build and publish Docker image

on: push
#  push:
#    tags:
#      - '**'

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 21
          architecture: x64
      - run: gradle build
      - run: docker login --username ${{secrets.DOCKER_USER}} --password ${{secrets.DOCKER_PASSWORD}} ${{secrets.REGISTRY_URL}}
      - run: docker build -t "${{secrets.REGISTRY_URL}}/ANEvdokimov/discount-watcher-server:test" .
      - run: docker push "${{secrets.REGISTRY_URL}}/ANEvdokimov/discount-watcher-server:test"
