name: Java CI

on: [ push ]

jobs:
  build_and_test_app:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: discount_watcher_server_test
          POSTGRES_PASSWORD: password-for-tests
          POSTGRES_DB: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v1
        with:
          java-version: 21
          architecture: x64
      - name: Test with Gradle
        run: gradle test
